### PR TITLE
provide submodel implementation for Handover documentation

### PR DESCRIPTION
**Pull request by chf73**
We use this submodel in a project and I would like to contribute it to the SDK.
DocumentVersion is not completely done yet, but I can at least share this current implementation.

### CODE REVIEW

**Comment by FrankSchnicke** [comment]
Thank you very much for providing this submodel implementation! Are you planning on extending the implementation whenever DocumentVersion is done?

**Comment by chf73** [comment]
> Thank you very much for providing this submodel implementation! Are you planning on extending the implementation whenever DocumentVersion is done?

Yes, I will extend it - however I cannot give a timeline yet ... maybe not in the next 2 weeks, but maybe then I will find the time 👍

**Comment by FrankSchnicke** [comment]
We will take a look and provide feedback. However, due to vacation, it may take 1-2 weeks. Feel free to update it in the meantime if you find the time 👍

**Comment by mdanish98** [comment]
Hi @chf73 

Thank you so much for your contribution.

We have prepared some remarks class-wise after carefully reviewing as below:

HandoverDocumentation:
- Additional constructor is missing for accepting the collection of Document and Entity.
- Additional overloaded methods are missing for addDocument and addEntity taking Collection as parameter

Document:
- DocumentId should be a list as per cardinality
- Setter is missing for DocumentClassification
- The First constructor violates the specification as there should be at least 1 DocumentId and 1 DocumentClassification
- The second constructor violates the specification as there should be at least 1 DocumentId and 1 DocumentClassification
- The third constructor should not have DocumentVersion as per the cardinality defined in the specification
- Attribute DocumentedEntity{00} is missing

DocumentClassification:
- Why is there a constructor with a Default access modifier?
- The classId, className, and classificationSystem are mandatory, so only one constructor should exist.
- As per specification, only one ClassId, ClassName, ClassificationSystem per DocumentClassification, but implemented in a way that it can accept any number. It should restrict if it is already set.
- No Getters specified for the attributes

DocumentId:
- Default idShort is missing.
- No Getters for the attributes
- One more constructor for parameters as SubmodelElements, i.e., Property ..
- As per specification, only 1 DocumentDomainId and only 1 ValueId per DocumentId, but implemented in a way that it can accept any number. It should restrict if it is already set.

DocumentVersion:
- Invalid constructors, ignoring mandatory attributes
- Incorrect value for the constant DOCUMENT_VERSION_IRDI
- Should have no spacing in the value of the constant DIGITAL_FILE_IRDI
- Should have no spacing in the value of the constant PREVIEW_FILE_IRDI
- Incorrect value for the constant BASED_ON_IRDI
- No implementation/setters for StatusSetDate, StatusValue, OrganizationName, OrganizationOfficialName, RefersTo, BasedOn, TranslationOf.
- As per specification, only 1 DocumentVersionId, Title, and Summary should be there but implemented in a way that it can accept any number. It should restrict if it is already set.

We will update this review remarks if we find something more.

**Comment by FrankSchnicke** [comment]
Hi @chf73, is this still something that you're working on?

**Comment by FrankSchnicke** [comment]
Closed due to inactivity. 

@chf73 if this gets relevant for you again, feel free to re-raise this PR any time.

**Pull request closed without merging**
