### PR TITLE
Add (further) setIdentification Method to ConceptDescription

### PR DESCRIPTION
**Pull request by seicke-harting**

### CODE REVIEW

**Comment by FrankSchnicke** [comment]
Thank you very much for your contribution. Would it be possible to sign the ECA?

**Comment by seicke-harting** [comment]
Yes, of course. Tried to create an eclipse account to sign the ECA.
Problem: the eclipse sender's address is on a RBL (reputation black list), so email ist blocked 😔

**Comment by FrankSchnicke** [comment]
Do you have any other mail that you can use? Alternatively, I can add your code to the code base - if this is fine with you.

**Comment by seicke-harting** [comment]
Problem solved, eclipse sender's address is no longer on a RBL.
ECA is signed.

**Comment by FrankSchnicke** [comment]
Perfect, thank you very much!

**Pull request merged**
