### PR TITLE
Fix CVE dependency issue

### PR DESCRIPTION
**Pull request by CVEDetect**
Fix issue #276  by update dependency poi-ooxml.version to 5.1.0 @FrankSchnicke

### CODE REVIEW

**Comment by FrankSchnicke** [comment]
Thanks for providing this PR. However, you're missing a signed ECA and the CI is failing with the upgrade. Would it be possible to take a look at these issues?

**Comment by FrankSchnicke** [comment]
ECA is passing, thanks. However, in your latest commit, you reverted your change and added another library - was this on accident?

**Comment by CVEDetect** [comment]
Because the vulnerability was introduced by org.apache.commons:commons-compress, which is a dependency of poi-ooxml. Due to significant changes in the first attempt to modify the poi-ooxml version, which caused a CI failure, I chose to directly upgrade the version of commons-compress in my second attempt at modification.

**Comment by FrankSchnicke** [comment]
Thanks a lot!

**Pull request merged**
